name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x64

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Build Windows executable
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Create Release Artifacts
        run: |
          mkdir release
          Copy-Item "build\app\outputs\apk\release\*" -Destination "release\" -Recurse
          Copy-Item "build\windows\x64\runner\Release\*" -Destination "release\" -Recurse

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}